apiVersion: apps/v1
kind: Deployment
metadata:
  name: searchapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: searchapi
  template:
    metadata:
      labels:
        app: searchapi
    spec:
      containers:
      - name: searchapi
        image: pial08/elasticsearchapi:latest
        ports:
        - containerPort: 8000